name: Classroom Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check if insert_books.js exists
        run: test -f insert_books.js

      - name: Check if queries.js exists
        run: test -f queries.js

      - name: Run insert_books.js
        run: |
          npm install mongodb
          node insert_books.js

      - name: Check basic query in queries.js
        run: |
          npm install mongodb
          grep -q "find({" queries.js && grep -q "genre:" queries.js

      - name: Check advanced query in queries.js
        run: |
          npm install mongodb
          grep -q "\$gt" queries.js && grep -q "\$and" queries.js

      - name: Check aggregation pipeline in queries.js
        run: |
          npm install mongodb
          grep -q "aggregate" queries.js && grep -q "\$group" queries.js

      - name: Check indexing in queries.js
        run: |
          npm install mongodb
          grep -q "createIndex" queries.js && grep -q "explain" queries.js